# Generated by Django 5.2.1 on 2025-06-30 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_mng_sys', '0004_alter_result_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('TERM-1', 'TERM-1')], max_length=20)),
                ('attendance', models.FloatField(default=0)),
                ('notebook', models.FloatField(default=0)),
                ('discipline', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch_mng_sys.student')),
            ],
        ),
    ]
