# Generated by Django 5.2.1 on 2025-07-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_mng_sys', '0005_internalmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmarks',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
